version: "3.8"

services:
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
      target: dev
    env_file: .env
    environment:
      NODE_ENV: development
      BIGCOMMERCE_CANONICAL_STORE_DOMAIN: ${BIGCOMMERCE_CANONICAL_STORE_DOMAIN}
      BIGCOMMERCE_API_URL: ${BIGCOMMERCE_API_URL}
      BIGCOMMERCE_CDN_HOSTNAME: ${BIGCOMMERCE_CDN_HOSTNAME}
      COMPANY_NAME: ${COMPANY_NAME}
      SITE_NAME: ${SITE_NAME}
      BIGCOMMERCE_STORE_HASH: ${BIGCOMMERCE_STORE_HASH}
      BIGCOMMERCE_CHANNEL_ID: ${BIGCOMMERCE_CHANNEL_ID}
      BIGCOMMERCE_ACCESS_TOKEN: ${BIGCOMMERCE_ACCESS_TOKEN}
      BIGCOMMERCE_CUSTOMER_IMPERSONATION_TOKEN: ${BIGCOMMERCE_CUSTOMER_IMPERSONATION_TOKEN}
      STRAPI_API_URL: ${STRAPI_API_URL}
      STRAPI_API_TOKEN: ${STRAPI_API_TOKEN}
      NEXT_PUBLIC_VERCEL_URL: ${NEXT_PUBLIC_VERCEL_URL}
      NEXT_PUBLIC_DEFAULT_REVALIDATE_TARGET: ${NEXT_PUBLIC_DEFAULT_REVALIDATE_TARGET}
    volumes:
      - ./web:/app
      - /app/node_modules
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - payload
    networks:
      - postgresNet

  payload:
    container_name: payload
    image: node:18-alpine
    working_dir: /app/
    command: sh -c "yarn install && yarn dev"
    env_file: .env
    environment:
      PORT: ${PAYLOAD_PORT}
      DATABASE_URI: ${PAYLOAD_URI}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
    ports:
      - '3300:3300'
    volumes:
      - ./payload:/app
      - /app/node_modules
    depends_on:
      - postgres
    networks:
      - postgresNet

  postgres:
    container_name: postgres
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:16-alpine
    hostname: postgresDB
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - payload-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - "5432:5432"
    networks:
      - postgresNet

volumes:
  payload-data:

networks:
  postgresNet:
    name: Payload Postgres 
    driver: bridge